- name: this play book will install configure deploy webpage on tomcat
  hosts: all
  tasks: 
     - name: Install apache2 in ubuntu machin
       apt: name=apache2 state=latest update_cache=yes

     - name: permissions to change
       file: path=/var/html state=directory mode=0777

     - name: Configure apache2 web root folder
       copy: src=000-default.conf dest=/etc/apache2/sites-available/000-default.conf

     - name: grant permissions for customwebfolder
       copy: src=apache2.conf dest=/etc/apache2/apache2.conf

     - name: restart apache
       service: name=apache2 status=started

     - name: deploy  our custom code
       template: src=index.html.j2 dest=/var/html/index.html
