- name: this play book will install configure deploy webpage on tomcat
  hosts: all
  tasks: 
     - name: Install apache2 in ubuntu machin
       apt: name=apache2 state=latest update_cache=yes

     - name: Start apache
       service: name=apache2 status=started

     - name: Configure apache2 web root folder
       copy: src=000-default.conf dest=/etc/apache2/sites-available/000-default.conf

     - name: grant permissions for customwebfolder
       copy: src=apache2.conf dest=/etc/apache2/apache2.conf

     - name: restart apache
       service: name=apache2 status=started
     
       
