- name: this play ping all docker containers
  hosts: all
  tasks:
    - name: Ping the container
      ping:

    - name: Print IP addres of container
      command: hostname -i
      register: output1
    
    - debug: var=output1
 
    - name: Print hostname of the container
      command: hostname
      register: output2
  
    - debug: var=output2
